### ISSUE TITLE
Make update crossing item match invision

### ISSUE THREAD

**Issue by briaguya** [cityofaustin/ctxfloods#126] opened 2018-02-21 20:18 UTC
https://projects.invisionapp.com/share/NHFQ3V1673T#/screens/273535315
![screen shot 2018-02-21 at 2 18 08 pm](https://user-images.githubusercontent.com/6384156/36503244-1188718c-1712-11e8-8b66-5f04ae5876cf.png)

**Comment by briaguya** [comment] 2018-02-21 20:20
Do the same for the list view (it's the same component)
![image](https://user-images.githubusercontent.com/6384156/36503303-4c19c3c8-1712-11e8-8a3c-fcf183bd4d12.png)

**Comment by luqmaan** [comment] 2018-02-26 21:42
Updated the icons and some fonts in https://github.com/cityofaustin/ctxfloods/pull/129.

But at this point this issue is a dupe of #135.

**Closed by luqmaan** 2018-02-26 21:42 UTC
