### ISSUE TITLE
Update community data

### ISSUE THREAD

**Issue by luqmaan** [cityofaustin/ctxfloods#247] opened 2018-04-16 19:40 UTC
The community data we're using is incorrect. For example, Bastrop County is in Africa.

**Comment by briaguya** [comment] 2018-04-17 05:45
I'm curious as to where this is an issue. [A community's viewport is updated every time a crossing is added to it](https://github.com/cityofaustin/ctxfloods-backend/blob/b59b9f4939e03ec5a8eb071b59b6fcc5fd91110f/populateDB/migrations/001_create-schema.sql#L569-L572), if anything we may need to update [add_crossing_to_community](https://github.com/cityofaustin/ctxfloods-backend/blob/b59b9f4939e03ec5a8eb071b59b6fcc5fd91110f/populateDB/migrations/001_create-schema.sql#L647) because it's missing that logic, but I doubt that would be the root cause of something as drastic as Bastrop in Africa.

**Comment by briaguya** [comment] 2018-04-17 06:59
I believe this should be resolved via #248

**Comment by briaguya** [comment] 2018-04-17 07:35
i was poking through the code on atxfloods and found this:
```
var latLngCOA = new google.maps.LatLng(30.267153,-97.743061);
var zoomCOA = 11;
var latLngTCO = new google.maps.LatLng(30.267153,-97.743061);
var zoomTCO = 10;
var latLngSSV = new google.maps.LatLng(30.219915,-97.817781);
var zoomSSV = 14;
var latLngCPK = new google.maps.LatLng(30.539135,-97.839088);
var zoomCPK = 14;
var latLngLEA = new google.maps.LatLng(30.589012,-97.829819);
var zoomLEA = 13;
var latLngRRK = new google.maps.LatLng(30.508255,-97.678896);
var zoomRRK = 13;
var latLngROL = new google.maps.LatLng(30.270002,-97.788749);
var zoomROL = 13;
var latLngWCO = new google.maps.LatLng(30.522415,-97.715004);
var zoomWCO = 11;
var latLngMBF = new google.maps.LatLng(30.578245,-98.2728);
var zoomMBF = 13;
var latLngHCO = new google.maps.LatLng(30.062155,-98.00121);
var zoomHCO = 10;
var latLngCCO = new google.maps.LatLng(29.837151,-97.620079);
var zoomCCO = 11;
var latLngBCO = new google.maps.LatLng(30.091640,-97.326958);
var zoomBCO = 11;
```

**Comment by Niicck** [comment] 2018-10-23 21:01
Resolved with https://github.com/cityofaustin/ctxfloods-backend/pull/28

**Closed by Niicck** 2018-10-23 21:01 UTC
Labels: score: 2
