### ISSUE TITLE
Bastrop Community select zooms incorrectly

### ISSUE THREAD

**Issue by wilhitem** [cityofaustin/ctxfloods#286] opened 2018-06-26 19:57 UTC
Problem:
When I click on the Bastrop community, it zooms incorrectly out. 

Steps to recreate:
1. open floods.austintexas.io
2. Click on 'communities' in top menu
3. click on 'Bastrop County'

expected behavior:
map view centers on bastrop and zooms appropriately.

actual behavior:
page zooms out. See screenshot of final view, I think this is because there is a data point with the lat/long reversed (see data point in china on refocus on far right of screenshot)
![screen shot 2018-06-26 at 2 52 51 pm](https://user-images.githubusercontent.com/1779067/41935830-c3631aa6-7950-11e8-9693-bf9c8f343549.png)

**Comment by luqmaan** [comment] 2018-06-26 21:14
Dupe of #247

**Closed by luqmaan** 2018-06-26 21:14 UTC
Labels: bug, score: 1
